[project]
name = "bog_connector"
authors = [
    { name = "Talorim", email = "shalva@talorim.com"}
]
description = "Bank of Georgia Business Online API integration for ERPNext: syncs account statements into Bank Transaction records."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "requests"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
